# Login to Azure subscription
name: 'Azure Login'
description: 'Azure Login wraps the az login, allowing Azure actions to log into Azure or to run Az CLI scripts. github.com/Azure/Actions'
inputs: 
  creds:
    description: 'Paste output of `az ad sp create-for-rbac` as value of secret variable: AZURE_CREDENTIALS'
    required: true
  cloud:
    description: 'Include the name of the Sovereign cloud that you would like to connect to:  Options include AzureUSGovernment, AzureChinaCloud, AzureGermanCloud'
    required: false
branding:
  icon: 'login.svg'
  color: 'blue'
runs:
  using: 'node12'
  main: 'lib/main.js'
