name: pr-check

on:
  pull_request:
    branches:
      - master
      - 'releases/*'
jobs:
   az-login-test:
     runs-on: windows-latest
     steps:
       - name: Checkout from PR branch  
         uses: actions/checkout@v6
         with: 
          repository: ${{ github.event.pull_request.head.repo.full_name }}
          ref: ${{ github.event.pull_request.head.ref }}

         # Using 24.x version as an example
       - name: Set Node.js 24.x for GitHub Action
         uses: actions/setup-node@v6
         with:
           node-version: 24.x

       - name: installing node_modules
         run: npm install 

       - name: Build GitHub Action
         run: npm run build
         
       - name: Run mock test
         run: npm run test
