#This workflow is used to test azure login action for CLI edge build. Visit, https://github.com/Azure/azure-cli#edge-builds for more details.

name: 'Scheduled: Azure Login Canary (CLI edge build)'
on: 
  workflow_dispatch:
  schedule:
    - cron:  '0 8 * * *'  
permissions:
      id-token: write
      contents: read
jobs: 
  az-login-test:
    runs-on: ubuntu-latest
    steps:
      - name : Check Az version before installing
        run: az --version
        
      - name: Installing Az CLI Edge build 
        run: |
           cd ../..
           CWD="$(pwd)"
           python3 -m venv canary-venv
           . canary-venv/bin/activate
           echo "***********activated virual environment**********" 
           python3 -m pip install --upgrade pip
           echo "***************started installing cli edge build******************"
           pip3 install -q --upgrade --pre azure-cli --extra-index-url https://azurecliprod.blob.core.windows.net/edge --no-cache-dir --upgrade-strategy=eager
           echo "***************installed cli Edge build*******************"    
           echo "$CWD/canary-venv/bin" >> $GITHUB_PATH
           az --version
           
      - name: Check out repository
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        
      - name: 'Az CLI login with subscription'
        uses: azure/login@7ddb5af1ef8758cf1353cf3b42f940aee27ba21c # v3.0.2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
          
      - run: |
          az account show --output none
          
      - name: 'Az CLI login without subscription'
        uses: azure/login@7ddb5af1ef8758cf1353cf3b42f940aee27ba21c # v3.0.2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
          allow-no-subscriptions: true
          
      - run: |
          az account show --output none
          
      - name: 'Az CLI login with subscription OIDC'
        uses: azure/login@7ddb5af1ef8758cf1353cf3b42f940aee27ba21c # v3.0.2
        with:
          client-id: ${{ secrets.AZURE_CLIENTID }}
          tenant-id: ${{ secrets.AZURE_TENANTID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTIONID }} 
        
      - run: |
          az account show --output none
          
      - name: 'Az CLI login without subscription OIDC'
        uses: azure/login@7ddb5af1ef8758cf1353cf3b42f940aee27ba21c # v3.0.2
        with:
          client-id: ${{ secrets.AZURE_CLIENTID }}
          tenant-id: ${{ secrets.AZURE_TENANTID }}
          allow-no-subscriptions: true
          
      - run: |
          az account show --output none
