name: Build and Test

on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master

jobs:
  build_test_job:
    name: 'Build and test job'
    runs-on: ${{ matrix.os }}
    strategy:
        matrix:
          os: [windows-latest, ubuntu-latest]
    steps:

    - name: 'Checking out repo code'
      uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

    - name: Set Node.js 24.x for GitHub Action
      uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 # v7.0.0
      with:
        node-version: 24.x

    - name: 'Validate build'
      run: |
        npm install
        npm run build

    - name: 'Run L0 tests'
      run: |
        npm run test
