name: Build and Test

on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master

jobs:
  build_test_job:
    name: 'Build and test job'
    runs-on: ${{ matrix.os }}
    strategy:
        matrix:
          os: [windows-latest, ubuntu-latest]
    steps:

    - name: 'Checking out repo code'
      uses: actions/checkout@d23441a48e516b6c34aea4fa41551a30e30af803 # v6.1.0

    - name: Set Node.js 24.x for GitHub Action
      uses: actions/setup-node@249970729cb0ef3589644e2896645e5dc5ba9c38 # v6.5.0
      with:
        node-version: 24.x

    - name: 'Validate build'
      run: |
        npm install
        npm run build

    - name: 'Run L0 tests'
      run: |
        npm run test
