name: Markdownlint

on: [push, pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16.x
      - name: Run Markdownlint
        run: |
          npm i -g markdownlint-cli2
          markdownlint-cli2 "**/*.md"
